# Welcome to Jekyll!
#

# Site settings
title: CodeLab
description:
  Experimenting with Code<br> in Orange County
owner: CodeLabOC # or company name
first_published: 2016 # if migrating another site, the year of your first publish
email: CodeLabOC@gmail.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://codelaboc.github.io/" # the base hostname & protocol for your site
social:
  twitter: https://www.twitter.com/codelaboc
  github: https://github.com/codelaboc/hellocodelab
  # linkedin-square: https://linkedin.com/in/<username>
  # facebook-official: https://facebook.com/<username>
  # google-plus-square: https://plus.google.com/u/0/+<username>
  #email: /contact/
  #flickr:
  #instagram:
  #youtube-square:
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #stubleupon:
  #delicious:
  #pied-piper:
  #digg:
  #soundcloud:
  #deviantart:
  #angellist:
  #tumblr-square:
  #stackexchange:
  #weibo:
  #trello:
  #foursquare:
  #linux:
  #bitbucket-square:
  #vk:
  #slack:
  #vine:
  #weixin:
  #yelp:
  #skyatlas:
  #leanpub:
  #connectdevelop:
  #ils:
  #forumbee:
  #tripadvisor:
  #amazon:

# Build settings
markdown: kramdown
#sass:
#  style: compressed
